blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/ritoban23/nextflow/security/policy
    about: Please report vulnerabilities through the security policy process.
